### ISSUE TITLE
wont download

### ISSUE THREAD

**Issue by obviously-shadow** [danielcobo/init#1]
hi, the package wont download

**Comment by danielcobo** [comment]
Can you give more details please? For example, the OS you're using, what error do you get, etc.

I just tested the command below and it downloads/installs just fine.
`npm install -g @danielcobo/init`

**Comment by danielcobo** [comment]
I checked it works. Unable to reproduce issue without any feedback. 

Feel free to reopen the issue with extra info and I'll have a look.
